version: "3.9"
services:
  # postgres database
  system-db:
    container_name: system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
  # Spring Application
  agu-data-system:
    container_name: agu-data-system
    depends_on:
      - system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://system-db:5432/postgres?user=postgres&password=postgres
      - FETCHER_URL=http://fetcher:8081/api
      - PREDICTION_URL=http://prediction:8082/api
      - API_URL=http://agu-data-system:8080/api/agus/create
      - SONAR_GAS_URL=https://sonorgas.thinkdigital.pt/dashboards/ca824027-c206-44b9-af54-cba5dc6edde7/viewer
      - CSV_PATH=./
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y tzdata && 
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && 
    java -jar /usr/app/AGUDataSystem-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"

  # Web App
  agu-data-system-web:
    container_name: agu-data-system-web
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-web
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
    depends_on:
      - system-db
      - agu-data-system
