version: "3.9"
services:
  # postgres database
  system-db:
    container_name: system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
  # Spring Application
  agu-data-system:
    container_name: agu-data-system
    depends_on:
      - system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://system-db:5432/postgres?user=postgres&password=postgres
      - FETCHER_URL=http://fetcher:8080/api
    ports:
      - "8081:8080"