version: "3.9"
services:

  # postgres database
  system-db:
    container_name: system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Lisbon  # Timezone set here for flexibility
    ports:
      - "5431:5432"

  # Spring Application
  agu-data-system:
    container_name: agu-data-system
    depends_on:
      - system-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - TZ=Europe/Lisbon  # Ensure the app uses the same timezone as the DB
      - DB_URL=jdbc:postgresql://system-db:5432/postgres?user=postgres&password=postgres
      - FETCHER_URL=http://fetcher:8080/api
      - PREDICTION_URL=http://agu-prediction-system:8080/api
      - API_URL=http://agu-data-system:8080/api/agus/create
      - SONAR_GAS_URL=https://sonorgas.thinkdigital.pt/dashboards/ca824027-c206-44b9-af54-cba5dc6edde7/viewer
      - CSV_PATH=/usr/app/scripts/script_values.csv
    entrypoint: ["/bin/sh", "-c", "/usr/app/setup-back-end.sh"]
    ports:
      - "8080:8080"

  # Web App
  agu-data-system-web:
    container_name: agu-data-system-web
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-web
    environment:
      - TZ=Europe/Lisbon  # Ensure the app uses the same timezone as the DB
      - REACT_APP_API_URL=http://agu-data-system:8080/api
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
    depends_on:
      - system-db
      - agu-data-system
