FROM postgres

ENV PORT=5432

USER postgres

WORKDIR /app

COPY code/sql/create-tables.sql /docker-entrypoint-initdb.d/1_create.sql
COPY code/sql/insert-values.sql /docker-entrypoint-initdb.d/2_insert-values.sql

COPY --chown=postgres:postgres /dockerfiles/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE $PORT