begin transaction;

-- Drop views
DROP VIEW IF EXISTS temperature_readings;
DROP VIEW IF EXISTS gas_readings;

-- Drop tables
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS measure;
DROP TABLE IF EXISTS provider;
DROP TABLE IF EXISTS tank;
DROP TABLE IF EXISTS agu;
DROP TABLE IF EXISTS dno;
DROP TABLE IF EXISTS loads;
DROP TABLE IF EXISTS transport_company;

-- Drop domains
DROP DOMAIN IF EXISTS CUI;
DROP DOMAIN IF EXISTS PHONE;
DROP DOMAIN IF EXISTS PERCENTAGE;
DROP DOMAIN IF EXISTS LONGITUDE;
DROP DOMAIN IF EXISTS LATITUDE;

commit;
