begin transaction;

-- Drop tables
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS scheduled_load CASCADE;
DROP TABLE IF EXISTS agu_transport_company CASCADE;
DROP TABLE IF EXISTS transport_company CASCADE;
DROP TABLE IF EXISTS measure CASCADE;
DROP TABLE IF EXISTS tank CASCADE;
DROP TABLE IF EXISTS provider CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS agu CASCADE;
DROP TABLE IF EXISTS dno CASCADE;

-- Drop domains
DROP DOMAIN IF EXISTS CUI;
DROP DOMAIN IF EXISTS PHONE;
DROP DOMAIN IF EXISTS PERCENTAGE;
DROP DOMAIN IF EXISTS LONGITUDE;
DROP DOMAIN IF EXISTS LATITUDE;

commit;
